# Generated by Django 2.2.4 on 2019-08-31 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('rate', models.FloatField()),
                ('isVeg', models.BooleanField()),
                ('category', models.CharField(max_length=50)),
                ('image', models.TextField()),
                ('is_available', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField()),
                ('valid_till', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_value', models.FloatField()),
                ('discount_on', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webpages.Dish')),
            ],
        ),
    ]
