# Generated by Django 2.2.4 on 2019-09-01 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0002_auto_20190831_0827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dish',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 1, 7, 35, 50, 184936)),
        ),
        migrations.AlterField(
            model_name='dish',
            name='image',
            field=models.TextField(null=True),
        ),
    ]
