# Generated by Django 2.2.4 on 2019-09-15 07:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webpages', '0004_auto_20190908_0751'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='dish',
            name='available_from',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 7, 32, 13, 969058)),
        ),
    ]
